### ISSUE TITLE
Values of Ableton device parameters are not updated on the E1 screen

### ISSUE THREAD

**Issue by khiryos** [xot/ElectraOne#2] opened 2023-12-17 11:31 UTC
Controlling device parameters works fine but nothing changes on the E1 when turning a knob.

Please note that it only affects Ableton devices. Each 3rd party plugin works as expected (it creates an on-the-fly preset and values change on the E1 when turning a knob).

E1 3.5 directly plugged (no USB hub)
Live 11.3.13
Windows 11 last update

**Comment by thinium** [comment] 2023-12-23 21:17
I also encountered this issue! On top of that, when I change the currently selected device, moving any knob will not change anything in Ableton Live. I need to first touch a slider on E1's touchscreen and then moving the knobs in order to actually change the values in Ableton Live, but the latest value is not reflected in E1.

E1 Firmware v3.5 Hardware 3.0
Mac M1, OS 13.4.1
Ableton Live 11.3.13

**Comment by xot** [comment] 2023-12-27 12:40
I'm not able to replicate this. What version of the remote script are you using? And @khiryos what hardware version of the E1 are you running (a mkI or mkII)? Are you able to switch between selected Ableton devices and is the newly selected device shown on the E1 with the correct values of the parameters? When you chan ge the value of a parameter  *within Ableton*, is the updated value of the parameter sent to the E1 and correctly displayed there?

**Comment by thinium** [comment] 2023-12-27 15:04
@xot where can I find the version number of the remote script? In VersionInfo.py it states: COMMITDATE='Tue Nov 14 12:06:55 CET 2023'

When I switch between selected Ableton devices, the newly selected device isn't reflected on the E1; it's still showing the previously selected one. Toggling between mixer and the device view updates the view. The device shown on the E1 always shows the the wrong values (mostly zero). Here is a photo of the E1:
![tempImageuoiszo](https://github.com/xot/ElectraOne/assets/1383198/3b21e309-cd9c-413e-9431-42451be3d029)

It looks like the E1 didn't get Ableton's update. This is how I configured MIDI in/out (Only check Remote as suggested in the README):
![Screenshot 2023-12-27 at 16 09 38](https://github.com/xot/ElectraOne/assets/1383198/0906b981-9441-4327-b079-c936f239952d)
)

**Comment by xot** [comment] 2023-12-27 16:46
```versioninfo.py``` indeed shows the remote script version. Recent enough so that's not it. Ableton MIDI settings look good too (and the fact that anything is uploaded at all and switching between mixer and device works means that MIDI communication works as intended. Can you send me the contents of the log file, i.e. ```/Users/<username>/AppData/Roaming/Ableton/Live 11.3.13/Log.txt``` where ```<username>``` is your username under windows?

**Comment by thinium** [comment] 2023-12-28 09:49
@xot I am on Mac, and here is the latest log:
[20231228T084139_5506.log](https://github.com/xot/ElectraOne/files/13785155/20231228T084139_5506.log)

there are a ton of python errors, so maybe it's related.

Here is a video showing how E1 behaves with the Ableton Remote script on my machine:
https://drive.proton.me/urls/4TWS0CQ5QC#F5iOX5w18ROu

**Comment by xot** [comment] 2023-12-28 11:47
Thank you for the video! But I'm baffled. Where/how did you get the log? It looks completely different from the Ableton Live log I am used to seeing under either Windows or MacOS...

**Comment by thinium** [comment] 2023-12-28 12:53
Oh sorry, where should I get the log on Mac? I got mine under: 
<username>/Application Support/Ableton/Live Reports/Usage/

**Comment by thinium** [comment] 2023-12-28 12:55
I found it! 
[Log.txt.zip](https://github.com/xot/ElectraOne/files/13786612/Log.txt.zip)

**Comment by xot** [comment] 2023-12-28 14:46
Thanks. The other log was actually quite useful too, and I think I found the bug ;-) There was a wrong initialisation to UNMAPPED_ID one config_mixer.py. I have committed a fix; can you check whether that works for you too?

**Comment by thinium** [comment] 2023-12-28 15:36
nice! I just run a quick test and it is working on my machine. The values on E1 is in sync with Live and switching devices updates the E1 screen too.

Loading custom presets also works fine now. Thanks so much for taking the time to fix it!

**Closed as completed** 2023-12-29 10:38 UTC
